on:
  push:
    branches:
    - main
---
jobs:
  wiki_action:
-   name: Wiki Action
-   uses: ubuntu-latest
  # You may pin to the exact commit or the version.
  # uses: ineshbose/wiki-action@1c2f272a66f2dbac4192de6760034d1f534d9af6
    with:
    # GitHub token
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Wiki directory
    WIKI_DIR: # optional, default is wiki
    # Exclude directories/files from wiki (also from sidebar)
    WIKI_IGNORE: # optional, default is 
    # Build sidebar
    AUTO_SIDEBAR: # optional
    # Exclude directories/files from sidebar
    SIDEBAR_IGNORE: # optional, default is 
